### ISSUE TITLE
display only keyboard

### ISSUE THREAD

**Issue by RickMason1** [Faylixe/pygame-vkeyboard#20]
Is it possible to display only the keyboard and not the top area also, and place my window above it?

I built a new model with the numbers,letters, "  Enter key " ,  " , "  , and  " . ",  which work very well without the resizing that you fixed a couple of days ago.

Thanx
Rick Mason

**Comment by anxuae** [comment]
Hi @RickMason1 

> Is it possible to display only the keyboard and not the top area also

Not for now, the keyboard always take 50% of the given surface

> and place my window above it?

If you split your window in 2 surfaces, one for the key board, and one for all your other sprits, yes it is possible

> I built a new model with the numbers,letters, " Enter key " , " , " , and " . ", which work very well without the resizing that you fixed a couple of days ago.

Not sure to understand, you means that your keyboard is not working well since my last fix? If so, can you give me more info about what's wrong?

**Comment by anxuae** [comment]
Hello @RickMason1 

I added a new parameter `height_ratio` to the `VKeyboardLayout` class. So you can set it to `1`, and your keyboard will cover the entire surface height.

Please re-open if you see some bugs
